### PR TITLE
Make promise lib optional

### PR DESCRIPTION
**Pull request by jsg2021**
Promise is a builtin global in ES6. Projects using babel have a transparent polyfill. Specifying a lib is more and more becoming unneeded.

### CODE REVIEW

**Comment by gaearon** [comment]
Isn't that exactly what `global` option allows?

**Comment by jsg2021** [comment]
yes, but it was required to be specified.

this just makes it assume the built in one, if the option is omitted.
lowering the barrier to use this.

:) was just a nice to have. no biggie if you decide to reject.

**Comment by gaearon** [comment]
1. Generally we should have one way of doing something. Making empty string _and_ `global` both work seems like a strange choice and would likely confuse the user.
2. Global promises aren't supported in old browsers. Novices might not know this. If the “default” usage (no parameters) encourages them to use global promises, it's likely they won't even know their code is broken until they ship to production. We need to make this choice explicit and make it visible in code reviews.

**Comment by gaearon** [comment]
That said I'm happy to accept a PR that amends the error message to mention you can specify `global` to use the global Promises that ship with the browser.

Something like

```
You need to specify your Promise library of choice, e.g. require("promise?bluebird!./file.js"). You can also specify "global" if your target browsers support native Promises or if you include a polyfill.
```

**Pull request closed without merging**
